platform:
  - x86
  - x64
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node --version && npm --version
  - mkdir c:\yasm
  - set PATH=%APPDATA%\npm;c:\yasm;%PATH%
  - set CI=true
  - npm update -g npm
  - if "%PLATFORM%" == "x64" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
  - if "%PLATFORM%" == "x86" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe
  - node --version && npm --version && yasm --version
  - git submodule init && git submodule update
  - npm install --build-from-source --msvs_version=2015 --verbose
matrix:
  fast_finish: true
build: off
shallow_clone: true
